---
- name: "Add the user {{ user_username }}"
  user:
    name: "{{ user_username }}"
    group: "{{ user_group if user_group is defined else omit }}"
    password: "{{ user_password if user_password is defined else omit }}"

- name: "Set the user {{ user_username }} SSH authorized_keys entry"
  include_role:
    name: dottgonzo.ansible_role_add_ssh_authorized_key
  vars:
    authorized_keys_entry: "{{ user_authorized_keys_entry }}"
    user_for_authorized_keys: "{{ user_username }}"
  when:
    - user_authorized_keys_entry is defined